# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [1.8, 1.11]

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Build
      run: mvn -B package --file pom.xml
      
